# Generated by Django 5.1 on 2025-01-17 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.FileField(upload_to='svg_icons/')),
                ('icon_background', models.CharField(blank=True, max_length=128, null=True)),
                ('title', models.CharField(max_length=128)),
                ('course_count', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'web_categories',
                'ordering': ['id'],
            },
        ),
    ]
