# Generated by Django 5.1 on 2025-01-17 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_categories_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'ordering': ['id'], 'verbose_name': 'categorie'},
        ),
    ]
