# Generated by Django 5.1 on 2025-01-20 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_category_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='star_rating',
            field=models.FileField(blank=True, null=True, upload_to='course_icons/'),
        ),
    ]
