# Generated by Django 5.1 on 2025-01-17 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_categories_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='icon_background',
        ),
    ]
