# Generated by Django 5.1 on 2025-01-18 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_remove_categories_icon_background'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='courses/images/')),
                ('title', models.CharField(max_length=128)),
                ('instructor', models.CharField(max_length=128)),
                ('rating', models.FloatField(default=0.0, help_text='Course rating out of 5.0')),
                ('total_ratings', models.PositiveIntegerField(default=0, help_text='Total number of ratings')),
                ('total_hours', models.PositiveIntegerField(help_text='Total hours of the courses')),
                ('total_lectures', models.PositiveIntegerField(help_text='Number of lecture in the course')),
                ('level', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='Beginner', max_length=32)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price of the course', max_digits=6)),
                ('star_icon', models.FileField(blank=True, null=True, upload_to='courses/icons/')),
            ],
        ),
        migrations.RenameModel(
            old_name='Categories',
            new_name='Category',
        ),
    ]
