# Generated by Django 5.1 on 2025-01-18 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_instructor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelTable(
            name='course',
            table='web_courses',
        ),
        migrations.AlterModelTable(
            name='instructor',
            table='web_instructors',
        ),
    ]
