# Generated by Django 5.1 on 2025-01-18 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_alter_course_options_alter_course_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='course_count',
            field=models.PositiveIntegerField(default=0, help_text='Total number of course count'),
        ),
    ]
