# Generated by Django 5.1 on 2025-01-21 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_course_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='author_icon',
            field=models.FileField(blank=True, null=True, upload_to='course_icons'),
        ),
    ]
