# Generated by Django 5.1 on 2025-01-18 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_alter_category_course_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.TextField(help_text='Testimonial quote provided by the user.')),
                ('image', models.ImageField(upload_to='testimonials/images/')),
                ('name', models.CharField(help_text='Name of the person giving the testimonial.', max_length=128)),
                ('role', models.CharField(help_text='Role or designation of the reviewer.', max_length=128)),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
                'db_table': 'testimonials',
                'ordering': ['id'],
            },
        ),
    ]
