# Generated by Django 5.1 on 2025-01-21 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_delete_coursedetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('it', 'Italian'), ('de', 'German')], max_length=5, unique=True)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='course',
            name='languages',
        ),
        migrations.AddField(
            model_name='course',
            name='languages',
            field=models.ManyToManyField(blank=True, to='web.language'),
        ),
    ]
