# Generated by Django 5.1 on 2025-01-21 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_language_remove_course_languages_course_languages'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='certification',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='course_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='instructor_bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instructor',
            name='reviews',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='instructor',
            name='total_courses',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
