# Generated by Django 5.1 on 2025-01-21 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_course_certification_course_course_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='reviews',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='role',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='total_courses',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='total_students',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
