# Generated by Django 5.1 on 2025-01-21 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0017_syllabus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('user_image', models.ImageField(blank=True, null=True, upload_to='reviews/')),
                ('rating', models.PositiveIntegerField(default=1)),
                ('review_date', models.DateField(auto_now_add=True)),
                ('description', models.TextField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_reviews', to='web.course')),
            ],
        ),
    ]
